---
- name: Configure kubeconfig file and add oc in .bash_aliases
  hosts: localhost
  become: false
  vars:
    master_dns: "master.lab.example.com"
  tasks:  
    - name: Modify kubeconfig to use master IP
      lineinfile:
        path: /home/ubuntu/.kube/config
        regexp: '^ *server: https://127\.0\.0\.1:6443'
        line: '    server: https://{{ master_dns }}:6443'
    - name: Ensure .bash_aliases file exists
      file:
        path: "{{ ansible_env.HOME }}/.bash_aliases"
        state: touch
        mode: '0644'
    - name: Add alias for kubectl
      lineinfile:
        path: "{{ ansible_env.HOME }}/.bash_aliases"
        line: "alias oc='kubectl'"
        state: present
    - name: Add alias for kubectl
      lineinfile:
        path: "{{ ansible_env.HOME }}/.bash_aliases"
        line: "alias k='kubectl'"
        state: present