---
- name: Setup Hosts
  hosts: all
  become: true
  ignore_errors: true
  tasks:
    - name: Append entries to /etc/hosts
      lineinfile:
        path: /etc/hosts
        line: "{{ item }}"
        state: present
      loop:
        - "10.10.2.10 master.lab.example.com master"
        - "10.10.2.201 node1.lab.example.com node1"
        - "10.10.2.202 node2.lab.example.com node2"
        - "10.10.2.30 workstation.lab.example.com workstation"