---
- name: Install kubectl on workstation
  hosts: localhost
  become: true
  tasks:
    - name: Download kubectl binary
      get_url:
        url: https://dl.k8s.io/release/v1.28.0/bin/linux/amd64/kubectl
        dest: /usr/local/bin/kubectl
        mode: '0755'
    - name: Verify kubectl installation
      command: kubectl version --client
      register: kubectl_output
      ignore_errors: true
    - name: Display kubectl version
      debug:
        msg: "{{ kubectl_output.stdout }}"

    # - name: Creating .kube directory
    #   file:
    #     path: /home/vagrant/.kube
    #     state: directory
    #     mode: '0755'
    #     owner: vagrant 
    #     group: vagrant